In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv("Streaming.csv")
#delete not needed columns
df=df.drop(['Unnamed: 0','Rotten Tomatoes','Type','Directors','Country','Runtime'],axis=1)

In [4]:
#delete rows with rating <6.0
df.drop(df.loc[df['IMDb']<6.0].index, inplace=True)
df.head(5)

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Language
0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","English,Japanese,French"
1,2,The Matrix,1999,18+,8.7,1,0,0,0,"Action,Sci-Fi",English
2,3,Avengers: Infinity War,2018,13+,8.5,1,0,0,0,"Action,Adventure,Sci-Fi",English
3,4,Back to the Future,1985,7+,8.5,1,0,0,0,"Adventure,Comedy,Sci-Fi",English
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,1,0,1,0,Western,Italian

In [5]:
#User Input
print('Welcome to Movie Roulette')
genres=input('Choose Movie Genres : Action,Drama,Thriller,Romance,Family')
language=input('Choose Movie Language: English, French, Spanish')

Welcome to Movie Roulette
Choose Movie Genres : Action,Drama,Thriller,Romance,FamilyAction
Choose Movie Language: English, French, SpanishEnglish

In [6]:
#Filter dataset with User input
df.dropna(subset=['Genres'], inplace=True)
df=df[df['Genres'].str.contains(genres)]

df.dropna(subset=['Language'],inplace=True)
df=df[df['Language'].str.contains(language)]
#save number of rows in rows
rows= df.shape[0]
rows=rows-1
print(rows)
#reset df index
df=df.reset_index()
df.head(5)

670

,index,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Language
0,0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","English,Japanese,French"
1,1,2,The Matrix,1999,18+,8.7,1,0,0,0,"Action,Sci-Fi",English
2,2,3,Avengers: Infinity War,2018,13+,8.5,1,0,0,0,"Action,Adventure,Sci-Fi",English
3,5,6,Spider-Man: Into the Spider-Verse,2018,7+,8.4,1,0,0,0,"Animation,Action,Adventure,Family,Sci-Fi","English,Spanish"
4,8,9,Raiders of the Lost Ark,1981,7+,8.4,1,0,0,0,"Action,Adventure","English,German,Hebrew,Spanish,Arabic,Nepali"

In [11]:
#pick random number from 0 row number
from numpy import random
x = random.randint(rows)
#select Movie with random number
movie= df.at[x,'Title']
year= df.at[x, 'Year']
yearint=str(year)
google= movie +' '+ yearint+' '+'streaming'
print(google)

Star Wars: The Force Awakens 2015 streaming

In [12]:
import webbrowser
url='https://www.google.de/search?q='
webbrowser.open(url+google)

True